before_build:
- cmd: >-
    git submodule update --init

    md build

    cd build

    cmake -Werror=dev ..

build_script:
  - cmd: cmake --build . --target everything

after_build:
  - cmd: cmake --build . --target package

artifacts:
  - path: DDNet-*.zip
    name: DDNet