image: Visual Studio 2015

before_build:
- cmd: |
    git submodule update --init

    md build32 & pushd build32
    cmake -Werror=dev -G "Visual Studio 14 2015" ..
    popd

    md build64 & pushd build64
    cmake -Werror=dev -G "Visual Studio 14 2015 Win64" ..
    popd

build_script:
  - cmd: cmake --build build32 --config Release --target everything
  - cmd: cmake --build build64 --condig Release --target everything

after_build:
  - cmd: cmake --build build32 --config Release --target package
  - cmd: cmake --build build64 --config Release --target package

artifacts:
  - path: build^/DDNet-*.zip
    name: DDNet